repos:
  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use the specific version of Black
    hooks:
      - id: black

  # Ruff linter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.7  # Use the specific version of Ruff
    hooks:
      - id: ruff
        args: ["--fix", "--line-length=88"]

  # Pre-commit hook itself
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: check-yaml  # Checks YAML file syntax
      - id: end-of-file-fixer  # Ensures files end with a newline
      - id: trailing-whitespace  # Removes trailing whitespace
